use serde_json::Value;

/// The representation of an entity's primary key, taken from the PK field's type.
/// A `Uuid` implicit id is generated client-side on insert (no auto-increment to read back);
/// `String` requires a caller-supplied id; `Integer` is a DB auto-increment.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum IdType {
    #[default]
    Integer,
    String,
    Uuid,
}

impl IdType {
    /// Resolve from a PK field type. `biginteger`/`smallinteger`/absent collapse to `Integer` —
    /// only `uuid` and `string` change insert/parse behavior.
    pub fn from_field_type(raw: &str) -> Self {
        match raw.trim().to_ascii_lowercase().as_str() {
            "uuid" => IdType::Uuid,
            "string" => IdType::String,
            _ => IdType::Integer,
        }
    }

    pub fn is_uuid(&self) -> bool {
        matches!(self, IdType::Uuid)
    }

    /// Whether the id is generated by the client and bound on insert (`Uuid`/`String`) rather than
    /// DB-assigned (`Integer` auto-increment). Client-supplied ids are the ones whose synthetic PK
    /// column must be registered for a converter bind cast; owning the decision here keeps the next
    /// id type from silently regressing that path.
    pub fn is_client_supplied(&self) -> bool {
        matches!(self, IdType::Uuid | IdType::String)
    }

    /// The datasource-type key the synthetic primary-key column carries — the key the converter
    /// map (and its dialect `bind_sql_cast`, e.g. postgres `::uuid`) is looked up by. Mirrors the
    /// JS `DatasourceSettings` reference-field shape so a client-supplied id of any type resolves
    /// its cast without the runtime re-deriving `== uuid`.
    pub fn datasource_type_str(&self) -> &'static str {
        match self {
            IdType::Uuid => "uuid",
            IdType::String => "string",
            IdType::Integer => "number",
        }
    }
}

pub fn parse_id(id_type: IdType, raw: &str) -> Result<Value, String> {
    match id_type {
        IdType::Integer => parse_positive_int(raw).map(Value::from),
        IdType::String => {
            let trimmed = raw.trim();
            if trimmed.is_empty() {
                Err("id: must be a non-empty string".to_string())
            } else {
                Ok(Value::String(trimmed.to_string()))
            }
        }
        IdType::Uuid => uuid::Uuid::parse_str(raw)
            .map(|u| Value::String(u.hyphenated().to_string()))
            .map_err(|_| "id: must be a valid uuid".to_string()),
    }
}

pub fn parse_positive_int(raw: &str) -> Result<i64, String> {
    let n: i64 = raw
        .parse()
        .map_err(|_| "id: must be a positive integer".to_string())?;
    if n <= 0 {
        return Err("id: must be a positive integer".to_string());
    }
    Ok(n)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn from_field_type_maps_representations() {
        assert_eq!(IdType::from_field_type("uuid"), IdType::Uuid);
        assert_eq!(IdType::from_field_type("UUID"), IdType::Uuid);
        assert_eq!(IdType::from_field_type("string"), IdType::String);
        assert_eq!(IdType::from_field_type("integer"), IdType::Integer);
        assert_eq!(IdType::from_field_type("biginteger"), IdType::Integer);
        assert_eq!(IdType::from_field_type(""), IdType::Integer);
        assert_eq!(IdType::from_field_type("nonsense"), IdType::Integer);
    }

    #[test]
    fn is_uuid_only_for_uuid() {
        assert!(IdType::Uuid.is_uuid());
        assert!(!IdType::Integer.is_uuid());
        assert!(!IdType::String.is_uuid());
    }

    #[test]
    fn datasource_type_str_maps_each_variant() {
        assert_eq!(IdType::Uuid.datasource_type_str(), "uuid");
        assert_eq!(IdType::String.datasource_type_str(), "string");
        assert_eq!(IdType::Integer.datasource_type_str(), "number");
    }

    #[test]
    fn is_client_supplied_for_uuid_and_string_only() {
        assert!(IdType::Uuid.is_client_supplied());
        assert!(IdType::String.is_client_supplied());
        assert!(!IdType::Integer.is_client_supplied());
    }

    #[test]
    fn parse_id_uuid_normalizes_hyphenated() {
        let v = parse_id(IdType::Uuid, "550E8400E29B41D4A716446655440000").unwrap();
        assert_eq!(
            v,
            Value::String("550e8400-e29b-41d4-a716-446655440000".to_string())
        );
        assert!(parse_id(IdType::Uuid, "not-a-uuid").is_err());
    }

    #[test]
    fn parse_id_integer_rejects_non_positive() {
        assert_eq!(parse_id(IdType::Integer, "5").unwrap(), Value::from(5i64));
        assert!(parse_id(IdType::Integer, "0").is_err());
        assert!(parse_id(IdType::Integer, "abc").is_err());
    }
}
